apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-rest-api-deployment
  labels:
    app: go-rest-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-rest-api
  template:
    metadata:
      labels:
        app: go-rest-api
    spec:
      containers:
        - name: go-rest-api
          image: vkunal/demos:go-api-f5821a3d
          ports:
          - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"